### Create Dense Layer

In [1]:
!pip install nnfs
!pip install matplotlib

Importing Libraries

In [2]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

Definition

A Dense layer (also called a Fully Connected layer) is a neural network layer where:

Every neuron is connected to all neurons in the previous layer

In [8]:
class Layer_Dense:
    # Initialization
    def __init__(self, n_inputs, n_neurons):
        self.weights  = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1,n_neurons))
    def forward(self, inputs):
    # Calculate output values from inputs, weights and biases
        self.output = np.dot(inputs, self.weights) + self.biases

Creating the Dataset and Dense Layer

In [9]:
X, y = spiral_data(samples=100, classes=3)
dense1 = Layer_Dense(2, 3)
dense1.forward(X)
print(dense1.output[:5])


[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-4.4172935e-05  1.7795961e-04 -3.9071703e-05]
 [ 3.0106357e-05  3.6696982e-04 -9.3701252e-05]
 [-3.6547382e-04  1.9415646e-04 -8.2500537e-06]
 [-5.0237903e-04  1.6941362e-04  1.2681631e-05]]
